"""instruments

Revision ID: 2ca9f40e464b
Revises: b3972add7f68
Create Date: 2021-03-09 14:53:26.827681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca9f40e464b'
down_revision = 'b3972add7f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketinstrument',
    sa.Column('figi', sa.String(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.Enum('rub', 'usd', 'eur', 'gbp', 'hkd', 'chf', 'jpy', 'cny', 'try_', name='currency'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('stock', 'currency', 'bond', 'etf', name='instrumenttype'), nullable=False),
    sa.PrimaryKeyConstraint('figi')
    )
    op.create_index(op.f('ix_marketinstrument_figi'), 'marketinstrument', ['figi'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketinstrument_figi'), table_name='marketinstrument')
    op.drop_table('marketinstrument')
    # ### end Alembic commands ###
