"""init

Revision ID: b3972add7f68
Revises: 
Create Date: 2021-03-08 13:52:26.253842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3972add7f68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Enum('done', 'decline', 'progress', name='operationstatus'), nullable=False),
    sa.Column('currency', sa.Enum('rub', 'usd', 'eur', 'gbp', 'hkd', 'chf', 'jpy', 'cny', 'try_', name='currency'), nullable=False),
    sa.Column('commission', sa.Numeric(), nullable=False),
    sa.Column('payment', sa.Numeric(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_executed', sa.Integer(), nullable=False),
    sa.Column('figi', sa.String(), nullable=False),
    sa.Column('instrument_type', sa.Enum('stock', 'currency', 'bond', 'etf', name='instrumenttype'), nullable=False),
    sa.Column('is_margin_call', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('operation_type', sa.Enum('buy', 'buy_card', 'sell', 'broker_commission', 'exchange_commission', 'service_commission', 'margin_commission', 'other_commission', 'pay_in', 'pay_out', 'tax', 'tax_lucre', 'tax_dividend', 'tax_coupon', 'tax_back', 'repayment', 'part_repayment', 'coupon', 'dividend', 'security_in', 'security_out', name='operationtypewithcommission'), nullable=False),
    sa.Column('broker_account_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_id'), 'operation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_id'), table_name='operation')
    op.drop_table('operation')
    # ### end Alembic commands ###
